# Claw Cloud Deployment Configuration
# This file contains the configuration for deploying to Claw Run Cloud

app:
  name: "agentic-rag-webui"
  description: "Agentic RAG with Knowledge Graph - Web UI"
  
# Container configuration
container:
  port: 5000
  health_check: "/health"
  
# Environment variables (set these in Claw Cloud console)
environment:
  # Database Configuration
  DATABASE_URL: "postgresql://user:password@host:port/database"
  
  # Neo4j Configuration
  NEO4J_URI: "neo4j+s://your-instance.databases.neo4j.io"
  NEO4J_USERNAME: "neo4j"
  NEO4J_PASSWORD: "your-password"
  
  # LLM Provider Configuration
  LLM_PROVIDER: "openai"
  LLM_BASE_URL: "https://api.openai.com/v1"
  LLM_CHOICE: "gpt-4o-mini"
  LLM_API_KEY: "your-api-key"
  
  # Embedding Configuration
  EMBEDDING_BASE_URL: "https://api.openai.com/v1"
  EMBEDDING_API_KEY: "your-api-key"
  EMBEDDING_MODEL: "text-embedding-3-small"
  
  # Application Configuration
  APP_ENV: "production"
  LOG_LEVEL: "INFO"
  APP_HOST: "0.0.0.0"
  APP_PORT: "8058"
  
  # Web UI Configuration
  API_BASE_URL: "http://localhost:8058"
  WEB_UI_PORT: "5000"
  WEB_UI_HOST: "0.0.0.0"
  
  # Vector Search Configuration
  VECTOR_DIMENSION: "1536"
  MAX_SEARCH_RESULTS: "10"
  
  # Session Configuration
  SESSION_TIMEOUT_MINUTES: "60"
  MAX_MESSAGES_PER_SESSION: "100"
  
  # Rate Limiting
  RATE_LIMIT_REQUESTS: "60"
  RATE_LIMIT_WINDOW_SECONDS: "60"
  
  # File Processing
  MAX_FILE_SIZE_MB: "10"
  ALLOWED_FILE_EXTENSIONS: ".md,.txt"
  
  # Chunking Configuration
  CHUNK_SIZE: "8000"
  CHUNK_OVERLAP: "800"
  MAX_CHUNK_SIZE: "25000"

# Resource requirements
resources:
  cpu: "1000m"  # 1 CPU core
  memory: "2Gi"  # 2GB RAM
  
# Scaling configuration
scaling:
  min_replicas: 1
  max_replicas: 3
  target_cpu_utilization: 70

# Networking
networking:
  expose_internet: true
  custom_domain: false  # Set to true if you want to use a custom domain
